version: "2"
volumes:
  influxdbdata:
  grafanadata:
services:
  influxdb:
    image: jgeiger/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "7777/udp:7777/udp"
    volumes:
      - influxdbdata:/var/lib/influxdb
  grafana:
    image: jgeiger/grafana
    ports:
      - "3000:3000"
    # volumes:
      # - grafanadata:/data
