version: "2"
volumes:
  influxdbdata:
services:
  influxdb:
    image: jgeiger/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "7777/udp:7777/udp"
    volumes:
      - influxdbdata:/var/lib/influxdb/
  telegraf:
    image: jgeiger/telegraf
    command:
      - "telegraf"
      - "-config"
      - "/etc/telegraf/telegraf.conf"
      - "-config-directory"
      - "/etc/telegraf/telegraf.d"
